name = "Epicast"
uuid = "cbb96616-a3d1-4d5e-a40b-9319cdaf6efd"
authors = ["Scottie Alexander <palexander@lanl.gov>"]
version = "0.1.0"

[deps]
EpicastTables = "7f8b32be-ad0a-4d41-97a2-963287e4efb7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
